---
# 数据库相关配置
db:
  host: 192.168.3.1
  port: 3306
  user: root
  passwd: 123456
  name: configout

# 线程池个数
threadPoolNum: 4

# 密钥长度为16 or 24 or 32
secretKey: '$p+et+^bgyzg-l%r!^=v(xums)760(u2'

# token 有效期(小时)
tokenExp: 24

# ipanel OAuth2
ipanel:
  oauth2_id: cc8aaafc56411111111111111111
  secret: 11111111111
  agent_id: 1
  code_url: https://test.com/connect/oauth2/authorize
  access_token_url: https://test.com/connect/oauth2/access_token/get_access_token
  user_info_url: https://test.com/user/getuserinfo
